spring:
  application:
    name: UNIFY
  jpa:
    show-sql: true
    ddl-auto: update
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=Unify;encrypt=false;trustServerCertificate=false"
    username: sa
    password: 123456
