spring:
  datasource:
     url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?characterEncoding=UTF-8&prepareThreshold=0
     username: postgres.mlafrkaocppdojtsyysc
     password: yulwsLvpq8BqQmuDoNpexrXk
     driver-class-name: org.postgresql.Driver
     hikari:
         maximum-pool-size: 5
         minimum-idle: 5
         connection-timeout: 25000
         idle-timeout: 600000
         max-lifetime: 1800000
         pool-name: HikariConnPool
         leak-detection-threshold: 2000
  jpa:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  data:
   mongodb:
     uri: "mongodb+srv://mddev:mddev123321@cluster0.vd4gu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
     database: unify_chat_app
     auto-index-creation: true
   mail:
     host: smtp.gmail.com
     port: 587
     username: ${MAIL_USERNAME}
     password: ${MAIL_PASSWORD}
     protocol: smtp
     properties:
       mail:
         smtp:
           auth: true
           starttls:
             enable: true
             required: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

jwt:
  signerKey: "5c6321fb6bdf294f41ef37aifc20d0113853e3d633dc475df1a9ab36be2ba817797942e337fe3407165"

var:
  allowedOrigin: http://localhost:3000

