spring:
  application:
    name: UNIFY
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?characterEncoding=UTF-8&prepareThreshold=0
    username: postgres.mlafrkaocppdojtsyysc
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 25000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariConnPool
      leak-detection-threshold: 2000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    mongodb:
      uri: "mongodb+srv://mddev:${MONGO_PASSWORD}@cluster0.vd4gu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: unify_chat_app
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  cache:
    type: redis
mail:
  host: smtp.gmail.com
  port: 587
  username: ninhnapc09333@gmail.com
  password: ${MAIL_PASSWORD}
  protocol: smtp
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
logging:
  level:
    org.springframework.http.converter.json: DEBUG
    com.zaxxer.hikari: TRACE

jwt:
  signerKey: ${JWT_KEY}

var:
  allowedOrigin: http://localhost:3000

supabase:
  url: https://mlafrkaocppdojtsyysc.supabase.co
  key: ${SUPABASE_KEY}

server:
  port: 8080
