spring:
  app:
    secret-key: '5c6321fb6bdf294f41ef37aifc20d0113853e3d633dc475df1a9ab36be2ba817797942e337fe3407165'
  datasource:
    url: 'jdbc:sqlserver://localhost:1433;databaseName=Unify;encrypt=false;trustServerCertificate=false'
    username: sa
    password: 123456
  jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.SQLServerDialect
      show-sql: true
