spring:
  datasource:
#    url: "jdbc:sqlserver://localhost:1433;databaseName=Unify;encrypt=false;trustServerCertificate=false"
#    username: sa
#    password: 123456
     url: jdbc:postgresql://unify-app-unify.h.aivencloud.com:14334/unify?characterEncoding=UTF-8&sslmode=require
     username: avnadmin
     password: AVNS_5w7cmKQFtagnfWwVQrn
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  data:
   mongodb:
     uri: "mongodb+srv://mddev:mddev123321@cluster0.vd4gu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
     database: unify_chat_app
     auto-index-creation: true
  mail:
   host: smtp.gmail.com
   port: 587
   username: ${MAIL_USERNAME}
   password: ${MAIL_PASSWORD}
   protocol: smtp
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
           required: true
jwt:
  signerKey: "5c6321fb6bdf294f41ef37aifc20d0113853e3d633dc475df1a9ab36be2ba817797942e337fe3407165"

var:
  allowedOrigin: http://localhost:3000