spring:
  datasource:
    url: 'jdbc:sqlserver://localhost:1433;databaseName=Unify;encrypt=false;trustServerCertificate=false'
    username: sa
    password: 123456
  jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
