import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import "@fortawesome/fontawesome-free/css/all.min.css";
import RootProviders from "@/components/provider/RootProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Unify",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

    return (
          <html lang="en" suppressHydrationWarning>
          <Head>
              <link
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
                  rel="stylesheet"
              />
              <title>Unify</title>
          </Head>
          <body
              className={`${geistSans.variable} ${geistMono.variable} flex w-full antialiased`}
          >
         <RootProviders>
             {children}
         </RootProviders>
          </body>
          </html>
  );
}
