import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "./lib/fontawesome"
import Head from "next/head";
import '@fortawesome/fontawesome-free/css/all.min.css';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Unify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          rel="stylesheet"
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex antialiased`}
      >
        <main className="w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
